// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKcgsWFXRILRKBDy8hwYxWNTNBnYrGIs',
    appId: '1:341065738245:web:22deb3c14be1058b4cd46c',
    messagingSenderId: '341065738245',
    projectId: 'flutter-iti-fbd78',
    authDomain: 'flutter-iti-fbd78.firebaseapp.com',
    storageBucket: 'flutter-iti-fbd78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTqMyDKMoTAI1tFt0fWCSl4U_i41AcTDU',
    appId: '1:341065738245:android:93f034da47ed24534cd46c',
    messagingSenderId: '341065738245',
    projectId: 'flutter-iti-fbd78',
    storageBucket: 'flutter-iti-fbd78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1--gcMr-8DxXTV94k7gw7UxVFb34F0UY',
    appId: '1:341065738245:ios:4791c5c824154f984cd46c',
    messagingSenderId: '341065738245',
    projectId: 'flutter-iti-fbd78',
    storageBucket: 'flutter-iti-fbd78.firebasestorage.app',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1--gcMr-8DxXTV94k7gw7UxVFb34F0UY',
    appId: '1:341065738245:ios:4791c5c824154f984cd46c',
    messagingSenderId: '341065738245',
    projectId: 'flutter-iti-fbd78',
    storageBucket: 'flutter-iti-fbd78.firebasestorage.app',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeKcgsWFXRILRKBDy8hwYxWNTNBnYrGIs',
    appId: '1:341065738245:web:f22493de2fc4ed734cd46c',
    messagingSenderId: '341065738245',
    projectId: 'flutter-iti-fbd78',
    authDomain: 'flutter-iti-fbd78.firebaseapp.com',
    storageBucket: 'flutter-iti-fbd78.firebasestorage.app',
  );
}
